name: BukkitBookSaver
main: com.graywolf336.BukkitBookSaver.BukkitBookSaverMain
version: maven-version-number
description: Need written books to be saved to file? I am your solution.
authors: [graywolf336]
load: POSTWORLD
api-version: 1.13
permissions:
  book-save:
    description: Allows a player to save a book to file
    default: op
  book-load:
    description: Allows a player to load a book from file
    default: op
commands:
    book-save:
        description: Saves a book to file.
    reload-book-saver:
        description: Reloads the config file for the Book Saver plugin.
    books-save-in-chest:
        description: Saves all of the books inside of the chest a player is looking at.
    books-load-serialized:
        description: Loads a serialized book.
    books-load-json:
        description: Loads a json seralized book.
