name: BukkitBookSaver
main: com.graywolf336.BukkitBookSaver.BukkitBookSaverMain
version: maven-version-number
description: Need written books to be saved to file? I am your solution.
authors: [graywolf336]
load: POSTWORLD
commands:
    save-book:
        description: Saves a book to file.
    reload-book-saver:
        description: Reloads the config file for the Book Saver plugin.
    save-books-in-chest:
        description: Saves all of the books inside of the chest a player is looking at.
